enum EnumActionTypes {
  FETCH_LAUNCH_LIST_START = "FETCH_LAUNCH_LIST_START",
  FETCH_LAUNCH_LIST_SUCCESS = "FETCH_LAUNCH_LIST_SUCCESS",
  FETCH_LAUNCH_LIST_ERROR = "FETCH_LAUNCH_LIST_ERROR",
}

export default EnumActionTypes;
